### ISSUE TITLE
Questions on how to implement?

### ISSUE THREAD

**Issue by davidham** [gpeden/awspec-kitchen-terraform#1]
Hi! Thanks so much for this, I found it very useful. I had a couple of quick questions for you:

- Do you set up and teardown the environment each time, or do you leave your environment running?
- I'm new to Test Kitchen and I don't understand it very well. It appears to be a generalized tool for setting up, testing, and destroying infrastructure, but it seems like these features are all also available in Terraform. Does it offer anything I'm missing?
- In my own setup, my tests are working pretty well, but they also seem a little brittle--if the test needs the ID or IP address of the thing being tested (like a `nat_gateway` or an `eip`) I need to create the thing first, then get the IP/IP and add it to the test, then run the test. Any way around this? Is there a way to read the input vars, or query the resources, so I don't have to hardcode things into the tests?

Thanks again for the slideshow and any advice you can offer.

**Comment by longrackslabs** [comment]
Hi David!

1: For the demo, i bring it up and tear it down.  if you are talking about other use cases (dev, test, prod), it depends what you mean by 'each time'.  
2: Test kitchen by itself doesn't 'do' anything on its own, its a framework to plug in tools that do it.  So you can use terraform, or chef, or puppet, or awespec, inspec, whatever.
3: Not sure how to do a test for a specific IP.

hope that helps, and glad you found this useful

**Comment by alexstanhope** [comment]
Hi George, great post.  Really like your thinking on integration tests.

I'm wrestling with an analogue for unit testing.  I'm trying to encourage my team to approach the development of infrastructure-as-code as they would application code.

Have you seen the "Top 3 Terraform Testing Strategies" post from Carlos @ Contino?  I'd like to find a way to unit test against the "terraform plan" output.  Do you think there's mileage in that?

**Comment by longrackslabs** [comment]
Hi alex,
I'll give a look to Carlos' post and a think on unit testing agains plan output.

In the mean time, have you checked out this TF Linter repo?  https://github.com/wata727/tflint  in the spirit of catching potential errors as far upstream as possible we like to have a linter step in the build pipeline.  

george
